name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.31.0
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  form_bloc:
    git:
      url: https://github.com/daninow/form_bloc
      ref: master
      path: packages/form_bloc
  equatable: ^2.0.7
  rxdart: ^0.28.0
  collection: ^1.19.1
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
